### PR TITLE
DOC: Specify return type of sftp.open() function

### PR DESCRIPTION
**Pull request by NamamiShanker**
Hey devs, thank you for creating this library. I went through the docs and found that the `sftp.open()` docs do not specify its return type. I made this simple PR. If you think it would help, you can merge it.

### CODE REVIEW

**Comment by pkittenis** [comment]
Hi there,

Thank you for the interest and PR. Left some comments.

**Review by pkittenis — CHANGES_REQUESTED** [review]
Please update cython generated code by installing dependencies with `pip install -U -r requirements_dev.txt` and running `pip install -e .`.

This will re-generate `session.c` from the `session.pyx` source. Changes to `session.c` should be committed as part of this PR.

See also [Cython code](https://github.com/ParallelSSH/ssh2-python/blob/master/.github/CONTRIBUTING.rst#cython-code) section of contributing guide.

**Comment by NamamiShanker** [comment]
Hey @pkittenis! Does this look good?

**Review by pkittenis — APPROVED** [review]

**Comment by pkittenis** [comment]
Looks good, thank you. :+1:

**Pull request merged**
