### PR TITLE
Don't take the length of None

### PR DESCRIPTION
**Pull request by j3pic**
Should fix https://github.com/ParallelSSH/ssh2-python/issues/86

### CODE REVIEW

**Comment by j3pic** [comment]
I just realized you have those `.c` files committed to the repo instead of generating them in the build. I have no idea how to compile `.pyx` to C.

**Comment by j3pic** [comment]
I have confirmed that it's possible to call `userauth_publickey_frommemory` with `None` for the host key.

**Comment by kdart-brt** [comment]
The maintainer seems to have disappeared. Should we fork it?

**Comment by pkittenis** [comment]
Thanks for the PR. This needs a short test to confirm functionality.

**Comment by pkittenis** [comment]
Done by #104

**Pull request closed without merging**
