### PR TITLE
Add multiple features, bug fixes and update libssh2 to the latest stable.

### PR DESCRIPTION
**Pull request by Red-M**
New PR at #94

### CODE REVIEW

**Comment by Red-M** [comment]
This should superseed #80 and #75 while fixing #89, #86 and adding new functions with docs and tests completed.

**Comment by Red-M** [comment]
This now also properly implements #58 by fixing the bug in #76.

**Comment by Red-M** [comment]
Also appears that the LFS allowance for travis and appveyor has run out.

**Comment by Red-M** [comment]
@pkittenis Is there something that I need to do that I've missed?

**Comment by llchan** [comment]
@pkittenis are you still maintaining this project?  This PR has been incubating for quite some time and fixes many outstanding issues.

@Red-M I appreciate the work put in here + to get it out on pypi so it's more easily accessible.  That said, would you mind cutting a new/edited PR in this repo that points to a commit before you made some of the renaming changes in your master branch?  It would be better to merge your changes here rather than forking off forever, and in its current state the PR has unrelated changes.

**Comment by Red-M** [comment]
@llchan I'd love to but GitHub doesn't support changing the target branch of a PR. I'll have to open a new one and reference it in an edit on the first post and in the new PR.

**Comment by Red-M** [comment]
Please see #94 instead of this PR as I've forked under a new name to publish on pypi.

**Pull request closed without merging**
